### ISSUE TITLE
fichier manquant

### ISSUE THREAD

**Issue by Antonin-NICOLAS** [KaarisMoiLeCrane/EcoleDirecte-Plus#1]
manifest.json requiert le fichier /popup/chromeExtensionPopupDevTools-ContentScript.js qui n'est pas sur github

**Comment by KaarisMoiLeCrane** [comment]
Bonjour @Antonin-NICOLAS (et joyeuses fêtes),

Je m'excuse pour le délai de ma réponse. En décembre, j'ai pris du recul par rapport au codage pour me concentrer sur mes examens.
J'ai récemment mis à jour la branche principale avec de nouvelles fonctionnalités et des optimisations issues des branches develop et features. Le problème du fichier manquant a donc été résolu (ce fichier est désormais présent, mais il est spécifique à la version de développement, car l'extension elle-même n'a pas de popup).

La dernière version (2.0.0) est disponible dans les releases du dépôt, avec des instructions si nécessaire. Vous pouvez la télécharger [ici](https://github.com/KaarisMoiLeCrane/EcoleDirecte-Plus/releases/tag/2.0.0).

Il s'agit d'une pré-release ; toutes les fonctionnalités sont opérationnelles, mais quelques ajustements mineurs peuvent encore être apportés avant la version finale.

Je suis à nouveau actif, donc n'hésite pas à me faire part de toute autre remarque ou question.

En espérant que tu reçois ce message malgré le délai, et n'hésite pas à partager l'extension avec d'autres personnes !
