### ISSUE TITLE
Problème de licence

### ISSUE THREAD

**Issue by Bastian-Noel** [KaarisMoiLeCrane/EcoleDirecte-Plus#2]
Bonjour @KaarisMoiLeCrane,

J'ai remarqué que tu utilises du code de mon extension, mais il semble y avoir quelques problèmes de licence. 

Je tiens à te faire savoir que j'apprécie ton projet et que l'utilisation de mon code ne me dérange pas. Cependant, il est important d'adapter certaines choses pour respecter les licences appropriées.

Bien cordialement, Bastian de CustomDirecte

**Comment by KaarisMoiLeCrane** [comment]
Bonjour @Bastian-Noel,

Je te remercie d'avoir pris le temps de me contacter concernant les problèmes de licence liés à l'utilisation de ton code dans mon projet. Je tiens à m'excuser pour tout désagrément que cela a pu causer. De plus, je tiens à admettre que, étant donné que mon projet est purement personnel, j'ai initialement choisi une licence de manière un peu aléatoire.

Ainsi, suite à ta notification (et à ta patience, j'étais concentré sur mes examens pour Parcoursup), j'ai effectué une modification de la licence de mon projet, passant à GPL v3, pour assurer la conformité avec ta licence. Cette transition devrait, en toute logique, résoudre les problèmes de licence que tu as identifié.

Je tiens également à t'exprimer mon appréciation pour ton projet. J'apprécie énormément le travail que tu as accompli et je suis reconnaissant de me permettre d'utiliser ton CSS. Étant peu expérimenté en design (voire totalement inconnu), ceci est d'une valeur inestimable pour améliorer l'apparence de la barre latérale et par conséquent de EcoleDirecte en général.

Je tiens également à préciser que je n'ai pas utilisé Discord, car je réserve son usage à des fins personnelles liées à mes études.

Cordialement, @KaarisMoiLeCrane

**Comment by Bastian-Noel** [comment]
Merci du changement !
